## configuraciones basicas
ventas:
  columns:
    año_mes: str
    cod_sector: str
    nombre_negocio: str
    cod_oficina: str
    nombre_oficina: str
    ventas_cop: float
    ventas_kg: float

meses:
  ENE: '01'
  FEB: '02'
  MAR: '03'
  ABR: '04'
  MAY: '05'
  JUN: '06'
  JUL: '07'
  AGO: '08'
  SEP: '09'
  OCT: '10'
  NOV: '11'
  DIC: '12'